frontend:
  targetNamespace: test2-www
  image:
    repository: gcr.io/ivankuchin/test-container
    pullPolicy: IfNotPresent
    tag: "v0.0.1234"
api:
  targetNamespace: test2-api
  image:
    repository: gcr.io/ivankuchin/test-container
    pullPolicy: IfNotPresent
    tag: "v0.0.4321"
openapi:
  targetNamespace: test2-openapi
  image:
    repository: gcr.io/ivankuchin/test-container
    pullPolicy: IfNotPresent
    tag: "v0.0.5678"
db:
  targetNamespace: test2-db
  image:
    repository: gcr.io/ivankuchin/test-container
    pullPolicy: IfNotPresent
    tag: "v0.0.8765"
